### ISSUE TITLE
Cant get it to compile on Ubuntu16 / AMD 17.50 SDK

### ISSUE THREAD

**Issue by Integrative** [daveahartley/BurstGPUPlotter#1]
When CMAKE / MAKE i get this

```
root@intmc1mine001:/opt/gpuPlotGenerator/build# cmake .. -DOpenCL_INCLUDE_DIR=/opt/AMDAPPSDK-3.0/include/CL -DOpenCL_LIBRARY=/opt/AMDAPPSDK-3.0/lib/x86_64
-- Found OpenCL: /opt/AMDAPPSDK-3.0/lib/x86_64 (found version "2.0") 
-- Configuring done
WARNING: Target "gpuPlotGenerator" requests linking to directory "/opt/AMDAPPSDK-3.0/lib/x86_64".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
-- Build files have been written to: /opt/gpuPlotGenerator/build
root@intmc1mine001:/opt/gpuPlotGenerator/build# make
Scanning dependencies of target gpuPlotGenerator
[  4%] Building CXX object CMakeFiles/gpuPlotGenerator.dir/Command.cpp.o
[  9%] Building CXX object CMakeFiles/gpuPlotGenerator.dir/CommandGenerate.cpp.o
In file included from /opt/gpuPlotGenerator/CommandGenerate.cpp:25:0:
/opt/gpuPlotGenerator/build/GenerationDevice.h:18:23: fatal error: constants.h: No such file or directory
compilation terminated.
CMakeFiles/gpuPlotGenerator.dir/build.make:86: recipe for target 'CMakeFiles/gpuPlotGenerator.dir/CommandGenerate.cpp.o' failed
make[2]: *** [CMakeFiles/gpuPlotGenerator.dir/CommandGenerate.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/gpuPlotGenerator.dir/all' failed
make[1]: *** [CMakeFiles/gpuPlotGenerator.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
